### PR TITLE
Check go version in CI

### PR DESCRIPTION
**Pull request by djmitche**
### What does this PR do?

See https://github.com/DataDog/datadog-agent/pull/14098.  Note that this won't pass until that PR lands.

### CODE REVIEW

**Comment by djmitche** [comment]
Hm, why did this pass?  Help?

**Comment by djmitche** [comment]
Ah, I spotted it --
```
No idea what 'check-go-version' is!
```
I thought the `-e` at the top of that script would cause it to exit on error, but I guess not?

**Review by bkabrda — APPROVED** [review]

**Comment by djmitche** [comment]
(I'll land this once https://github.com/DataDog/datadog-agent/pull/14098 lands)

**Comment by djmitche** [comment]
Green means go!

**Pull request merged**
