### PR TITLE
Use notarytool for notarization

### PR DESCRIPTION
**Pull request by chouquette**
### What does this PR do?

This PR migrates from the legacy notarization method using `altool` to `notarytool`.

### Motivation

Legacy notarization will stop working on 2023/11/01

### Additional Notes

Since `notarytool` introduces a `--wait` option, we do not need to implement the polling ourselves, which causes most of the code to go away

### Possible Drawbacks / Trade-offs

altool (or most likely the backend on Apple's side) was sending an email following a successful notarization. The new tool will *not*.
We could achieve a similar result using `--webhook` or simply craft the mail as part of the script, but it isn't implemented so far.

### CODE REVIEW

**Review by spencergilbert — COMMENTED** [review]
🤔 I don't see where we're using the new `notarytool`?

**Comment by chouquette** [comment]
> thinking I don't see where we're using the new `notarytool`?

That's because I forgot to change that part :facepalm:

**Review by spencergilbert — APPROVED** [review]
Hah, I'm glad I wasn't losing my mind - presuming it all works as expected a very nice simplifications. Should we open a followup issue regarding the webook/email?

**Comment by chouquette** [comment]
I feel like I should clarify this: I haven't tested it yet as I'm running linux. Since the change is fairly easy I was hopping to get away with the CI results without spawning a VM

Regarding the followup task, do we care about receiving an email for each notarized build? That's also something that we can discuss in the followup task though :)

**Review by spencergilbert — APPROVED** [review]
LGTM!

**Pull request merged**
